# Generated by Django 3.0.5 on 2021-03-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': 'Continen', 'verbose_name_plural': 'Continents'},
        ),
    ]
