# Generated by Django 3.0.5 on 2021-03-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0002_auto_20210316_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': 'Continent'},
        ),
    ]
