# Generated by Django 3.0.5 on 2021-03-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0003_auto_20210316_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continent',
            old_name='polulation',
            new_name='population',
        ),
    ]
