# Generated by Django 3.0.5 on 2021-04-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0004_auto_20210319_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continent',
            old_name='history',
            new_name='overview',
        ),
    ]
