# Generated by Django 3.0.5 on 2021-05-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0005_auto_20210427_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='continent',
            name='place',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
