# Generated by Django 3.0.5 on 2021-05-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0007_auto_20210524_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='first_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
