# Generated by Django 3.0.5 on 2021-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0008_auto_20210524_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='first_image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='third_image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
