# Generated by Django 3.0.5 on 2021-05-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0009_auto_20210524_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='first_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='continent',
            name='second_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='continent',
            name='third_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
